server {
    listen 80;

    location = /specs/auth.json {
        proxy_pass http://film-auth:8080/swagger/v1/swagger.json;
    }

    location = /specs/movies.json {
        proxy_pass http://film-movies:8080/swagger/v1/swagger.json;
    }

    location = /specs/comments.json {
        proxy_pass http://film-comments:8080/swagger/v1/swagger.json;
    }

    location = /specs/search.json {
        proxy_pass http://film-search:8080/swagger/v1/swagger.json;
    }

    location = /specs/collections.json {
        proxy_pass http://film-collections:8080/swagger/v1/swagger.json;
    }

    location = /specs/merged.json {
        proxy_pass http://film-swagger-merger:8081/merged.json;
    }

    location / {
        proxy_pass http://film-swagger-ui:8080/;
    }
}
