# mongod.conf
storage:
  dbPath: /data/db

net:
  bindIp: 0.0.0.0  # Разрешаем подключения с любых IP
  port: 27017
  maxIncomingConnections: 1000000
  # bindIpAll: true  # альтернативный способ

security:
  authorization: enabled  # Включаем авторизацию

# Для дополнительной безопасности можно ограничить доступ по IP через iptables/firewall