import type { Collection } from "../types";

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: '1',
    createDate: new Date('2024-01-15'),
    updateDate: new Date('2024-02-20'),
    name: 'Любимые фильмы',
    sourceCollectionId: 'source_1',
    userId: 'user_123',
    movies: ['tt0111161', 'tt0068646', 'tt0071562'],
    tags: ['драма', 'классика'],
    isPublic: true,
    isCommentable: true,
    isCopiable: true,
    isByFilmograf: false,
    isDeleted: false,
    moviePreviews: [],
  },
  {
    id: '2',
    createDate: new Date('2024-01-20'),
    updateDate: new Date('2024-02-25'),
    name: 'Нолан',
    sourceCollectionId: 'source_2',
    userId: 'user_123',
    movies: ['tt0468569', 'tt1375666', 'tt1856101'],
    tags: ['триллер', 'фантастика'],
    isPublic: true,
    isCommentable: false,
    isCopiable: false,
    isByFilmograf: true,
    isDeleted: false,
    moviePreviews: [],
  },
  {
    id: '3',
    createDate: new Date('2024-02-01'),
    updateDate: new Date('2024-02-28'),
    name: 'Скрытые жемчужины',
    sourceCollectionId: 'source_3',
    userId: 'user_456',
    movies: ['tt1130884', 'tt0945513', 'tt1213644'],
    tags: ['инди', 'артхаус'],
    isPublic: false,
    isCommentable: true,
    isCopiable: true,
    isByFilmograf: false,
    isDeleted: false,
    moviePreviews: [],
  },
  {
    id: '4',
    createDate: new Date('2024-02-10'),
    updateDate: new Date('2024-03-01'),
    name: 'Марвел',
    sourceCollectionId: 'source_4',
    userId: 'user_789',
    movies: ['tt4154796', 'tt3498820', 'tt2395427'],
    tags: ['экшн', 'супергерои'],
    isPublic: true,
    isCommentable: true,
    isCopiable: true,
    isByFilmograf: false,
    isDeleted: false,
    moviePreviews: [],
  },
  {
    id: '5',
    createDate: new Date('2024-02-15'),
    updateDate: new Date('2024-03-05'),
    name: 'Аниме шедевры',
    sourceCollectionId: 'source_5',
    userId: 'user_101',
    movies: ['tt0245429', 'tt0119698', 'tt0205671'],
    tags: ['аниме', 'анимация'],
    isPublic: true,
    isCommentable: true,
    isCopiable: false,
    isByFilmograf: true,
    isDeleted: false,
    moviePreviews: [],
  },
  {
    id: '6',
    createDate: new Date('2024-02-20'),
    updateDate: new Date('2024-03-10'),
    name: 'Удаленная коллекция',
    sourceCollectionId: 'source_6',
    userId: 'user_202',
    movies: ['tt0109830', 'tt0118799'],
    tags: ['комедия'],
    isPublic: false,
    isCommentable: false,
    isCopiable: false,
    isByFilmograf: false,
    isDeleted: true, 
    moviePreviews: [],
  },
];
